### ISSUE TITLE
Bitballon ruby gem is crashing

### ISSUE THREAD

**Issue by znmeb** [BitBalloon/bitballoon-ruby#9]
```
$ bitballoon deploy
/home/znmeb/.gem/ruby/gems/bitballoon-0.2.4/bin/bitballoon:8:in `block in <top (required)>': undefined method `on' for main:Object (NoMethodError)
	from /home/znmeb/.gem/ruby/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
	from /home/znmeb/.gem/ruby/gems/slop-4.0.0/lib/slop.rb:24:in `new'
	from /home/znmeb/.gem/ruby/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
	from /home/znmeb/.gem/ruby/gems/bitballoon-0.2.4/bin/bitballoon:7:in `<top (required)>'
	from /home/znmeb/bin/bitballoon:23:in `load'
	from /home/znmeb/bin/bitballoon:23:in `<main>'
```

**Comment by biilmann** [comment]
Thanks for reporting this! The option parsing gem, slop, released a new version with changes to its syntax and we didn't specify a specific version in our gemspec.

I've pushed a new version of the gem that fixes this.

**Comment by znmeb** [comment]
working now - thanks!!
